pub const DEFAULT_CREDS: &[(&str, &str)] = &[
    ("root", "root"),
    ("admin", "admin"),
    ("user", "user"),
    ("guest", "guest"),
    ("root", "1234"),
    ("admin", "1234"),
    ("support", "support"),
    ("telnet", "telnet"),
    ("admin", "password"),
    ("root", "password"),
    ("root", "toor"),
    ("realtek", "realtek"),
    ("root", "12345"),
    ("admin", "12345"),
    ("root", "54321"),
    ("supervisor", "supervisor"),
    ("ubnt", "ubnt"),
];
